# Generated by Django 6.0.5 on 2026-05-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_document_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_document_photo_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_document_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_id_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='selfie_photo_url',
        ),
    ]
