# Generated by Django 6.0.5 on 2026-06-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_id_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guest_average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guest_rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
