# Generated by Django 6.0.5 on 2026-05-14 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(default='Nairobi', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('display_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('display_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price_per_night_kes', models.PositiveIntegerField()),
                ('price_per_week_kes', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_month_kes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_guests', models.PositiveIntegerField(default=1)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('amenities', models.JSONField(default=list)),
                ('house_rules', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(default=list)),
                ('verification_badges', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('live', 'Live'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
