# Generated by Django 6.0.5 on 2026-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='display_latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='display_longitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
        migrations.AddField(
            model_name='listing',
            name='area_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
