# Generated by Django 6.0.5 on 2026-06-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='earliest_checkin_time',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='listing',
            name='earliest_checkout_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='listing',
            name='hourly_blocks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='hourly_min_hours',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='hourly_pricing_type',
            field=models.CharField(blank=True, choices=[('flat_rate', 'Flat Rate per Hour'), ('fixed_blocks', 'Fixed Time Blocks')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='hourly_rate_kes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_hourly_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='latest_checkin_time',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='listing',
            name='latest_checkout_time',
            field=models.TimeField(default='11:00'),
        ),
    ]
