# Generated by Django 6.0.5 on 2026-06-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_earliest_checkin_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='long_stay_discounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
