# Generated by Django 6.0.5 on 2026-07-01

from django.db import migrations
from django.db.models import Avg


def make_all_reviews_visible_and_recalc(apps, schema_editor):
    Review = apps.get_model('reviews', 'Review')
    User = apps.get_model('users', 'User')
    HostProfile = apps.get_model('users', 'HostProfile')

    # Make legacy hidden reviews visible now that double-blind is removed.
    Review.objects.filter(is_visible=False).update(is_visible=True)

    # Recalculate guest ratings for all users.
    for user in User.objects.all():
        qs = Review.objects.filter(reviewee=user, is_visible=True)
        avg = qs.aggregate(Avg('rating'))['rating__avg']
        count = qs.count()

        if user.role == 'host':
            try:
                host_profile = HostProfile.objects.get(user=user)
                host_profile.average_rating = round(avg, 2) if avg else 0
                host_profile.save(update_fields=['average_rating'])
            except HostProfile.DoesNotExist:
                pass
        else:
            user.guest_average_rating = round(avg, 2) if avg else None
            user.guest_rating_count = count
            user.save(update_fields=['guest_average_rating', 'guest_rating_count'])


def noop_reverse(apps, schema_editor):
    # Do not hide reviews again on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_booking_fk_and_unique'),
        ('users', '0004_user_guest_average_rating_user_guest_rating_count'),
    ]

    operations = [
        migrations.RunPython(make_all_reviews_visible_and_recalc, noop_reverse),
    ]
