# Generated by Django 6.0.5 on 2026-05-14 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_nights', models.PositiveIntegerField()),
                ('total_amount_kes', models.PositiveIntegerField()),
                ('platform_fee_kes', models.PositiveIntegerField()),
                ('host_payout_kes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('awaiting_host', 'Awaiting Host'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending_payment', max_length=20)),
                ('mpesa_transaction_code', models.CharField(blank=True, max_length=50, null=True)),
                ('host_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_release_at', models.DateTimeField(blank=True, null=True)),
                ('payout_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
