# Generated by Django 6.0.5 on 2026-06-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
