# Generated by Django 6.0.5 on 2026-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_payment_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('sent', 'Sent')], default='not_applicable', max_length=20),
        ),
    ]
