# Generated by Django 6.0.5 on 2026-06-25 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('commercial', 'Commercial'), ('villa', 'Villa')], default='apartment', max_length=20)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(default='Nairobi', max_length=100)),
                ('area_description', models.CharField(blank=True, max_length=255, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('size_sqft', models.IntegerField(blank=True, null=True)),
                ('sale_price_kes', models.BigIntegerField()),
                ('is_also_for_rent', models.BooleanField(default=False)),
                ('monthly_rent_kes', models.BigIntegerField(blank=True, null=True)),
                ('installments_available', models.BooleanField(default=False)),
                ('photos', models.JSONField(default=list)),
                ('amenities', models.JSONField(default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('seller_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('seller_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('live', 'Live'), ('sold', 'Sold'), ('suspended', 'Suspended')], default='pending_review', max_length=20)),
                ('verification_badges', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_for_sale', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to='sales.propertysale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
